postly/core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("", include("post.urls", namespace="post")),
    path("", include("userprofile.urls", namespace="profile")),
    path("accounts/", include("allauth.urls")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

postly/post/urls.py
from django.urls import path

from post import views

app_name = "post"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("create_post/", views.create_post, name="create_post"),
    path("post_list/<str:username>", views.user_posts, name="user_posts"),
    path(
        "following_posts/<str:username>",
        views.following_posts,
        name="following_posts",
    ),
    path("post_detail/<int:post_id>", views.post_detail, name="post_detail"),
    path("post/<int:post_id>/edit", views.edit_post, name="edit_post"),
    path("post/<int:post_id>/delete", views.delete_post, name="delete_post"),
    path(
        "comment/<int:comment_id>/delete",
        views.delete_comment,
        name="delete_comment",
    ),
    path(
        "comment/<int:comment_id>/edit",
        views.edit_comment,
        name="edit_comment",
    ),
    path("like_post/<int:post_id>", views.like_post, name="like_post"),
    path(
        "dislike_post/<int:post_id>", views.dislike_post, name="dislike_post"
    ),
    path(
        "like_comment/<int:comment_id>",
        views.like_comment,
        name="like_comment",
    ),
    path(
        "dislike_comment/<int:comment_id>",
        views.dislike_comment,
        name="dislike_comment",
    ),
]

postly/userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = "profile"

urlpatterns = [
    path("profile/<username>", views.profile, name="profile"),
    path(
        "userprofile/<username>/edit", views.edit_profile, name="edit_profile"
    ),
    path(
        "activate_profile_validation/<uidb64>/<token>",
        views.activate_profile_validation,
        name="activate_profile_validation",
    ),
    path(
        "activate_profile/",
        views.activate_profile,
        name="activate_profile",
    ),
    path("follow/<int:profile_id>", views.follow, name="follow"),
    path("unfollow/<int:profile_id>", views.unfollow, name="unfollow"),
    path("followers/<int:profile_id>", views.followers, name="followers"),
    path("following/<int:profile_id>", views.following, name="following"),
]

postly/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("register/", views.registration, name="register"),
    path(
        "confirm_email/<str:email>", views.confirm_email, name="confirm_email"
    ),
    path("login/", views.login_view, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path(
        "reset_password_validation/<uidb64>/<token>/",
        views.reset_password_validation,
        name="reset_password_validation",
    ),
    path("reset_password/", views.reset_password, name="reset_password"),
    path(
        "resend_verification_email/<str:email>",
        views.resend_verification_email,
        name="resend_verification_email",
    ),
    path("change_email/<str:email>", views.change_email, name="change_email"),
]

postly/templates/includes/header.html
{% load static %}

<header>
   <nav class="navbar navbar-expand-lg bg-dark fixed-top" data-bs-theme="dark">
        <a class="navbar-brand postly-brand" href="{% url 'post:post_list' %}">Postly</a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'post:user_posts' request.user.username %}">My Posts</a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'post:following_posts' request.user.username %}">Following feed</a>
                    </li>

                     <li class="nav-item dropdown ">
                            <a class="nav-link dropdown-toggle text-white" href="#" role="button"
                                data-bs-toggle="dropdown" aria-expanded="false">
                                My profile
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item  text-white" href="{% url 'post:create_post' %}">Create post</a></li>
                                <li><a class="dropdown-item  text-white" href="{% url 'profile:profile' request.user.username %}">Profile</a></li>
                                {% if user.is_admin or user.is_staff %}
                                    <li><a class="dropdown-item  text-white" href="{% url 'admin:index' %}">Admin</a></li>
                                {% endif %}
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <form method="post" action="{% url 'users:logout' %}" class="mt-4">
                                        {% csrf_token %}
                                        <button class="dropdown-item  text-white" type="submit" >Logout</button>
                                    </form>
                                </li>
                            </ul>
                        </li>

                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

postly/templates/includes/non_field_errors.html
{% if form.non_field_errors %}
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="alert alert-danger alert-dismissible fade show custom-shadow" role="alert">
                    {{ form.non_field_errors }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
    </div>
{% endif %}

postly/templates/includes/notifications.html
{% load static %}

<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow show-notification" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                    {% if message.tags == 'warning' %}
                    <div id="notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow show-notification" role="alert">
                        {{ message }}
                    </div>
                    {% endif %}
                {% endfor %}
            {% else %}
            <div id="jq-notification" class="position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow show-notification" style="display: none;" role="alert">
            </div>
            {% endif %}
        </div>
    </div>
</div>