postly/core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("", include("post.urls", namespace="post")),
    path("", include("userprofile.urls", namespace="profile")),
    path("accounts/", include("allauth.urls")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

postly/post/urls.py
from django.urls import path

from post import views

app_name = "post"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("create_post/", views.create_post, name="create_post"),
    path("post_list/<str:username>", views.user_posts, name="user_posts"),
    path(
        "following_posts/<str:username>",
        views.following_posts,
        name="following_posts",
    ),
    path("post_detail/<int:post_id>", views.post_detail, name="post_detail"),
    path("post/<int:post_id>/edit", views.edit_post, name="edit_post"),
    path("post/<int:post_id>/delete", views.delete_post, name="delete_post"),
    path(
        "comment/<int:comment_id>/delete",
        views.delete_comment,
        name="delete_comment",
    ),
    path(
        "comment/<int:comment_id>/edit",
        views.edit_comment,
        name="edit_comment",
    ),
    path("like_post/<int:post_id>", views.like_post, name="like_post"),
    path(
        "dislike_post/<int:post_id>", views.dislike_post, name="dislike_post"
    ),
    path(
        "like_comment/<int:comment_id>",
        views.like_comment,
        name="like_comment",
    ),
    path(
        "dislike_comment/<int:comment_id>",
        views.dislike_comment,
        name="dislike_comment",
    ),
]

postly/userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = "profile"

urlpatterns = [
    path("profile/<username>", views.profile, name="profile"),
    path(
        "userprofile/<username>/edit", views.edit_profile, name="edit_profile"
    ),
    path(
        "activate_profile_validation/<uidb64>/<token>",
        views.activate_profile_validation,
        name="activate_profile_validation",
    ),
    path(
        "activate_profile/",
        views.activate_profile,
        name="activate_profile",
    ),
    path("follow/<int:profile_id>", views.follow, name="follow"),
    path("unfollow/<int:profile_id>", views.unfollow, name="unfollow"),
    path("followers/<int:profile_id>", views.followers, name="followers"),
    path("following/<int:profile_id>", views.following, name="following"),
]

postly/post/models/comment.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models


class Comment(models.Model):

    content = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)

    post = models.ForeignKey(
        "post.Post", on_delete=models.CASCADE, related_name="comments"
    )

    owner = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="comments"
    )

    likes = GenericRelation("post.Like", related_name="liked_comment")
    dislikes = GenericRelation("post.Dislike", related_name="disliked_comment")

postly/post/models/dislike.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models


class Dislike(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    owner = models.ForeignKey(
        "users.User",
        on_delete=models.SET_NULL,
        null=True,
        related_name="dislikes",
    )

postly/post/models/like.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models


class Like(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)

    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")

    owner = models.ForeignKey(
        "users.User",
        on_delete=models.SET_NULL,
        null=True,
        related_name="likes",
    )

postly/post/models/post.py
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models


class Post(models.Model):

    title = models.CharField(max_length=100)
    content = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    owner = models.ForeignKey(
        "users.User", on_delete=models.CASCADE, related_name="posts"
    )

    tags = models.ManyToManyField("post.Tag", related_name="posts")

    likes = GenericRelation("post.Like", related_name="liked_post")
    dislikes = GenericRelation("post.Dislike", related_name="disliked_post")

    class Meta:
        ordering = ("id",)

    def __str__(self):
        return self.title

postly/post/models/post_image.py
from django.db import models


class Image(models.Model):

    image = models.ImageField(upload_to="post_image/", blank=True, null=True)

    post = models.ForeignKey(
        "post.Post", on_delete=models.CASCADE, related_name="images"
    )

postly/post/models/tag.py
from django.db import models


class Tag(models.Model):

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

postly/post/forms/comment.py
from django import forms

from post.models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("content",)

postly/post/forms/post.py
from django import forms

from post.models import Post


class PostForm(forms.ModelForm):
    tags = forms.CharField(max_length=255, required=False)
    images = forms.FileField(required=False)

    class Meta:
        model = Post
        fields = ("title", "content")

postly/post/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseRedirect,
    JsonResponse,
)
from django.shortcuts import redirect, render

from post.forms import CommentForm, PostForm
from post.models import Comment, Image, Post, Tag
from post.selectors import (
    get_dislike,
    get_following_posts,
    get_like,
    get_post_by_id,
    get_post_comments,
    get_posts,
    get_user_posts,
)

from users.models import User


@login_required(login_url="users:login")
def create_post(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.owner = request.user
            post.save()

            images = request.FILES.getlist("images")
            if images:
                for image in images:
                    Image.objects.create(image=image, post=post)

            tag_names = form.cleaned_data["tags"].split(",")
            for tag_name in tag_names:
                tag_name = tag_name.strip()
                if tag_name:
                    tag, _ = Tag.objects.get_or_create(name=tag_name)
                    post.tags.add(tag)

            return redirect("post:post_list")
    else:
        form = PostForm()

    return render(request, "post/create_post.html", {"form": form})


def post_list(request: HttpRequest) -> HttpResponse:
    page = request.GET.get("page", settings.DEFAULT_PAGE)
    search_value = request.GET.get("search", None)
    order_by = request.GET.get("order_by", None)
    posts = get_posts(search_value, order_by)

    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    current_page = paginator.page(int(page))

    return render(request, "post/post_list.html", {"posts": current_page})


def user_posts(request: HttpRequest, username: str) -> HttpResponse:
    page = request.GET.get("page", settings.DEFAULT_PAGE)
    search_value = request.GET.get("search", None)
    order_by = request.GET.get("order_by", None)
    user = User.objects.get(username=username)
    posts = get_user_posts(user, search_value, order_by)

    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    current_page = paginator.page(int(page))

    if request.user == user:
        return render(
            request,
            "post/my_posts.html",
            {"posts": current_page, "user": user},
        )

    return render(
        request, "post/user_posts.html", {"posts": current_page, "user": user}
    )


@login_required(login_url="users:login")
def following_posts(request: HttpRequest, username: str) -> HttpResponse:
    page = request.GET.get("page", settings.DEFAULT_PAGE)
    search_value = request.GET.get("search", None)
    order_by = request.GET.get("order_by", None)
    user = User.objects.get(username=username)

    posts = get_following_posts(user, search_value, order_by)

    paginator = Paginator(posts, settings.POSTS_PER_PAGE)
    current_page = paginator.page(int(page))

    return render(request, "post/following_feed.html", {"posts": current_page})


@login_required(login_url="users:login")
def post_detail(
    request: HttpRequest, post_id: int
) -> HttpResponse | HttpResponseRedirect:
    try:
        post = get_post_by_id(post_id)
    except ObjectDoesNotExist:
        messages.error(request, f"Post {post_id} not exist")
        return redirect("post:post_list")

    comments = get_post_comments(post)
    comment_form = CommentForm()

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.owner = request.user
            comment.save()
            return redirect("post:post_detail", post_id=post_id)

    return render(
        request,
        "post/post_detail.html",
        {
            "post": post,
            "Post": Post,
            "Comment": Comment,
            "comments": comments,
            "comment_form": comment_form,
        },
    )


@login_required(login_url="users:login")
def edit_post(
    request: HttpRequest, post_id: int
) -> HttpResponse | HttpResponseRedirect:
    try:
        post = Post.objects.get(id=post_id)
    except ObjectDoesNotExist:
        messages.error(request, f"Post {post_id} not exist")
        return redirect("post:post_list")

    if request.user != post.owner:
        messages.error(request, "You do not have permission to do this.")
        return redirect("post:post_list")

    if request.method == "POST":
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():

            tag_names = form.cleaned_data["tags"].split(",")
            for tag_name in tag_names:
                tag_name = tag_name.strip()
                if tag_name:
                    tag, _ = Tag.objects.get_or_create(name=tag_name)
                    post.tags.add(tag)

            images = request.FILES.getlist("images")
            if images:
                recent_images = Image.objects.filter(post=post)
                recent_images.delete()
                for image in images:
                    Image.objects.create(image=image, post=post)

            form.save()
            messages.success(request, "Post updated successfully.")
            return redirect("post:user_posts", post.owner.username)
    else:
        form = PostForm(instance=post)

    return render(
        request,
        "post/edit_post.html",
        {
            "form": form,
            "post": post,
        },
    )


@login_required(login_url="users:login")
def delete_post(
    request: HttpRequest, post_id: int
) -> HttpResponse | HttpResponseRedirect:
    try:
        post = Post.objects.get(id=post_id)
    except ObjectDoesNotExist:
        messages.error(request, f"Post {post_id} not exist")
        return redirect("post:post_list")

    if request.user != post.owner:
        messages.error(request, "You do not have permission to do this.")
        return redirect("post:post_list")

    if request.method == "POST":
        post.delete()
        return redirect("post:user_posts", post.owner.username)

    return render(
        request,
        "post/delete_post.html",
        {"post": post, "user": post.owner},
    )


@login_required(login_url="users:login")
def like_post(
    request: HttpRequest, post_id: int
) -> JsonResponse | HttpResponseRedirect:
    try:
        post = Post.objects.get(id=post_id)
    except ObjectDoesNotExist:
        messages.error(request, f"Post {post_id} not exist")
        return redirect("post:post_list")

    dislike, like, like_created = get_like(post, request.user)

    if dislike:
        dislike.delete()

    if like_created:
        like.save()
    else:
        like.delete()

    return JsonResponse(
        {
            "success": True,
            "like_count": post.likes.count(),
            "dislike_count": post.dislikes.count(),
        }
    )


@login_required(login_url="users:login")
def dislike_post(
    request: HttpRequest, post_id: int
) -> JsonResponse | HttpResponseRedirect:
    try:
        post = Post.objects.get(id=post_id)
    except ObjectDoesNotExist:
        messages.error(request, f"Post {post_id} not exist")
        return redirect("post:post_list")

    like, dislike, dislike_created = get_dislike(post, request.user)

    if like:
        like.delete()

    if dislike_created:
        dislike.save()
    else:
        dislike.delete()

    return JsonResponse(
        {
            "success": True,
            "like_count": post.likes.count(),
            "dislike_count": post.dislikes.count(),
        }
    )


@login_required(login_url="users:login")
def edit_comment(
    request: HttpRequest, comment_id: int
) -> HttpResponse | HttpResponseRedirect:
    try:
        comment = Comment.objects.get(id=comment_id)
    except ObjectDoesNotExist:
        messages.error(request, f"Comment {comment_id} not exist")
        return redirect("post:post_list")

    if request.user != comment.owner:
        messages.error(request, "You do not have permission to do this.")
        return redirect("post:post_list")

    if request.method == "POST":
        form = CommentForm(instance=comment, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("post:post_detail", comment.post.id)

    else:
        form = CommentForm(instance=comment)

    return render(
        request, "post/edit_comment.html", {"form": form, "comment": comment}
    )


@login_required(login_url="users:login")
def delete_comment(
    request: HttpRequest, comment_id: int
) -> HttpResponseRedirect:
    try:
        comment = Comment.objects.get(id=comment_id)
    except ObjectDoesNotExist:
        messages.error(request, f"Comment {comment_id} not exist")
        return redirect("post:post_list")

    if request.user != comment.owner:
        messages.error(request, "You do not have permission to do this.")
        return redirect("post:post_list")

    comment.delete()
    return redirect("post:post_detail", comment.post.id)


@login_required(login_url="users:login")
def like_comment(
    request: HttpRequest, comment_id: int
) -> JsonResponse | HttpResponseRedirect:
    try:
        comment = Comment.objects.get(id=comment_id)
    except ObjectDoesNotExist:
        messages.error(request, f"Comment {comment_id} not exist")
        return redirect("post:post_list")

    dislike, like, like_created = get_like(comment, request.user)

    if dislike:
        dislike.delete()

    if like_created:
        like.save()
    else:
        like.delete()

    return JsonResponse(
        {

postly/post/templates/post/create_post.html
{% extends 'base.html' %}

{% block title %}Create post{% endblock %}

{% block content %}
<h2>Create post</h2>

<form method="post" action="{% url 'post:create_post' %}" enctype="multipart/form-data">

    {% include 'includes/non_field_errors.html' %}

    {% csrf_token %}
    <div class="form-group mb-3">
        <label for="id_title">Title:</label>
        <input type="text" name="title" maxlength="100" required id="id_title" class="form-control" placeholder="Title">
    </div>

    <div class="form-group mb-3">
        <label for="id_content">Content:</label>
        <textarea name="content" cols="40" rows="10" required id="id_content" class="form-control" placeholder="Your content"></textarea>
    </div>

    <div class="form-group mb-3">
        <label for="id_tags">Tags:</label>
        <input type="text" name="tags" maxlength="255" id="id_tags" class="form-control" placeholder="Your tags">
    </div>

    <div class="mb-3">
        <label for="formFileMultiple" class="form-label">Images:</label>
        <input class="form-control" type="file" id="formFileMultiple" multiple name="images">
    </div>


    <button type="submit" class="btn btn-primary">Create</button>
</form>

{% endblock %}

postly/post/templates/post/delete_post.html
{% extends 'base.html' %}

{% block title %}Delete Post{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            <h2 class="card-title">Delete "{{ post.title }}"</h2>
            <p class="card-text">Are you sure you want to delete the post "{{ post.title }}"?</p>

            <form method="post" class="mb-3" action="{% url 'post:delete_post' post.id %}">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger">Delete</button>
            </form>

            <p class="card-text"><a href="{% url 'post:user_posts' user.username %}" class="btn btn-secondary">Cancel</a></p>
        </div>
    </div>
{% endblock %}

postly/post/templates/post/edit_comment.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Edit comment{% endblock %}

{% block content %}
    <div class="card post-card">
        <div class="card-header">
            <h2 class="add-comment-heading">Edit Comment</h2>
        </div>
        <div class="card-body">
            <form method="post" class="comment-form" action="{% url 'post:edit_comment' comment.id %}">

                {% include 'includes/non_field_errors.html' %}

                {% csrf_token %}

                <div class="mb-3">
                    <label for="id_content" class="form-label">Comment Content</label>
                    <textarea name="content" rows="4" required id="id_content" class="form-control" style="resize: none;">{{ form.content.value }}</textarea>
                </div>

                <div class="mb-3">
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

postly/post/templates/post/edit_post.html
{% extends 'base.html' %}

{% block title %}Edit Post{% endblock %}

{% block content %}
<h2>Edit Post</h2>
<div class="card">
    <div class="card-body">
        <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate action="{% url 'post:edit_post' post.id %}">

            {% include 'includes/non_field_errors.html' %}

            {% csrf_token %}

            <div class="form-group mb-3">
                <label for="id_title">Title:</label>
                <input type="text" name="title" value="{{ form.title.value }}" maxlength="100" required id="id_title" class="form-control">
                <div class="invalid-feedback">Please provide a title.</div>
            </div>

            <div class="form-group mb-3">
                <label for="id_content">Content:</label>
                <textarea name="content" cols="40" rows="5" required id="id_content" class="form-control" style="resize: none;">{{ form.content.value }}</textarea>

            </div>

            <div class="form-group mb-3">
                <label for="id_tags">Tags:</label>
                <input type="text" name="tags" maxlength="255" id="id_tags" class="form-control">
            </div>

            <div class="mb-3">
                <label for="formFileMultiple" class="form-label">Images:</label>
                <input class="form-control" type="file" id="formFileMultiple" multiple name="images">

                {% if form.image.errors %}
                    <div class="invalid-feedback">Please choose a valid image file.</div>
                {% endif %}
            </div>

            <button type="submit" class="btn btn-primary">Save Changes</button>
        </form>
    </div>
</div>
{% endblock %}

postly/post/templates/post/following_feed.html
{% extends 'base.html' %}

{% block title %}Following feed{% endblock %}

{% block content %}
{% if posts %}
    <h1 class="mb-4">Following feed</h1>
    {% include 'post/includes/posts_display.html' %}
{% else %}
    <h2>There is no posts yet, you can follow to other users</h2>
{% endif %}
{% endblock %}

postly/post/templates/post/my_posts.html
{% extends 'base.html' %}

{% block title %}My posts{% endblock %}

{% block content %}

    {% if posts %}
        <h1 class="mb-4">My Posts</h1>
        {% include 'post/includes/posts_display.html' %}
    {% else %}
        <h2>There is no posts yet, you can <a href="{% url 'post:create_post' %}">create</a> one</h2>
    {% endif %}

{% endblock %}

postly/post/templates/post/post_detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Post {{ post.title }}{% endblock %}

{% block content %}
    <div class="card post-card">
        <div class="card-body">
        <div class="row">
            <h2 class="card-title col">{{ post.title }}</h2>
            <p class="col text-end"><small class="text-muted">Date: {{ post.creation_date }} | Owner:
            <a href="{% url 'profile:profile' post.owner.username %}">{{ post.owner.username }}</a></small></p>
        </div>

            <div class="card-group pb-4 m-2">
            {% if post.images.all %}
                <div class="image-gallery">
                    {% for image in post.images.all %}
                        <img src="{{ image.image.url }}" alt="Image" class="img-fluid rounded" width="150" height="150">
                    {% endfor %}
                </div>
            {% endif %}
            </div>
            <div class="card-text m-2">
                <p>{{ post.content }}</p>
            </div>

            {% if post.tags %}
                <div class="tag-section m-2 pb-4">
                    <span class="tag-heading">Tags:</span>
                    {% for tag in post.tags.all %}
                        <span>{{ tag.name }}</span>
                    {% endfor %}
                </div>
            {% endif %}

            <div>
                {% csrf_token %}
                <a href="#" data-url="{% url 'post:like_post' post.id %}" data-post-id="{{ post.id }}" class="like-button no-decoration">
                    <img src="{% static 'deps/images/like-button.png' %}" alt="Like" class="like-icon small-icon">
                </a>
                <span class="like-count" id="like-count-{{ post.id }}">{{ post.likes.count }}</span>

                <a href="#" data-url="{% url 'post:dislike_post' post.id %}" data-post-id="{{ post.id }}" class="dislike-button no-decoration">
                    <img src="{% static 'deps/images/dislike-button.png' %}" alt="Dislike" class="dislike-icon small-icon">
                </a>
                <span class="dislike-count" id="dislike-count-{{ post.id }}">{{ post.dislikes.count}}</span>
            </div>
        </div>

        {% if request.user == post.owner %}
            <div class="btn-group">
                <a href="{% url 'post:edit_post' post.id %}" class="btn btn-secondary btn-sm">Edit post</a>
                <a href="{% url 'post:delete_post' post.id %}" class="btn btn-danger btn-sm">Delete post</a>
            </div>
        {% endif %}

        <div class="card-footer">
            <h3 class="comments-heading">Comments</h3>
            <div class="comments-section m-3">
                {% for comment in comments %}
                    <div class="comment">
                        <p>
                            <a href="{% url 'profile:profile' comment.owner.username %}">{{ comment.owner.username }}</a>:
                            {{ comment.content }}
                        </p>

                        {% if request.user == comment.owner %}
                            <a href="{% url 'post:edit_comment' comment.id %}" class="no-decoration">Edit</a>
                            <a href="{% url 'post:delete_comment' comment.id %}" class="no-decoration">Delete</a>
                        {% endif %}

                        <p class="comment-actions">
                             <a href="#" data-url="{% url 'post:like_comment' comment.id %}" data-comment-id="{{ comment.id }}" class="like-comment-button no-decoration">
                             <img src="{% static 'deps/images/like-button.png' %}" alt="Like_comment" class="like-icon small-icon">
                             </a>
                             <span id="like-comment-count-{{ comment.id }}">{{ comment.likes.count }}</span>
                             <a href="#" data-url="{% url 'post:dislike_comment' comment.id %}" data-comment-id="{{ comment.id }}" class="dislike-comment-button no-decoration">
                                 <img src="{% static 'deps/images/dislike-button.png' %}" alt="Dislike_comment" class="dislike-icon small-icon">
                            </a>
                            <span id="dislike-comment-count-{{ comment.id }}">{{ comment.dislikes.count }}</span>
                        </p>
                    </div>
                {% endfor %}
            </div>

            <h4 class="add-comment-heading">Add Comment</h4>
            <form method="post" class="comment-form" action="{% url 'post:post_detail' post.id %}">
                {% csrf_token %}

                <div class="form-group">
                    <textarea name="content" rows="4" required id="id_content" class="form-control" style="resize: none;" placeholder="Content"></textarea>
                </div>

                <div class="m-2">
                    <button type="submit" class="btn btn-primary">Comment</button>
                </div>
            </form>
        </div>
    </div>
    
    <script src="{% static 'deps/js/like_post.js' %}"></script>    
    <script src="{% static 'deps/js/like_comment.js' %}"></script>
{% endblock %}

postly/post/templates/post/post_list.html
{% extends 'base.html' %}

{% block title %}Post List{% endblock %}

{% block content %}
        {% if posts or request.GET.search %}
            <h1 class="mb-4">Post List</h1>
            {% include 'post/includes/posts_display.html' %}
        {% else %}
            <h2>There is no posts yet, you can <a href="{% url 'post:create_post' %}">create</a> one</h2>
        {% endif %}

{% endblock %}

postly/post/templates/post/user_posts.html
{% extends 'base.html' %}

{% block title %}{{ user.username }} posts{% endblock %}

{% block content %}

    {% if posts %}
        <h1 class="mb-4">{{ user.username }} Posts</h1>
        {% include 'post/includes/posts_display.html' %}
    {% else %}
        <h2>{{ user.username }} has no posts yet</h2>
    {% endif %}

{% endblock %}