postly/core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("", include("post.urls", namespace="post")),
    path("", include("userprofile.urls", namespace="profile")),
    path("accounts/", include("allauth.urls")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

postly/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users import views

app_name = "users"

urlpatterns = [
    path("register/", views.registration, name="register"),
    path(
        "confirm_email/<str:email>", views.confirm_email, name="confirm_email"
    ),
    path("login/", views.login_view, name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("forgot_password/", views.forgot_password, name="forgot_password"),
    path(
        "reset_password_validation/<uidb64>/<token>/",
        views.reset_password_validation,
        name="reset_password_validation",
    ),
    path("reset_password/", views.reset_password, name="reset_password"),
    path(
        "resend_verification_email/<str:email>",
        views.resend_verification_email,
        name="resend_verification_email",
    ),
    path("change_email/<str:email>", views.change_email, name="change_email"),
]

postly/users/models.py
from django.contrib.auth.base_user import BaseUserManager
from django.contrib.auth.models import AbstractBaseUser
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, username, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(username=username, email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self.create_user(username, email, password, **extra_fields)

    def get_by_natural_key(self, username):
        return self.get(username=username)


class User(AbstractBaseUser):

    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField(max_length=100, unique=True)

    activate_profile = models.BooleanField(default=False)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    is_superuser = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    USERNAME_FIELD = "username"

    objects = UserManager()

    def has_perm(self, perm, obj=None):
        return self.is_superuser

    def has_module_perms(self, app_label):
        return True

postly/users/forms/email.py
from django import forms

from users.models import User


class EmailForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ("email",)

postly/users/forms/login.py
from django.contrib.auth.forms import AuthenticationForm

from users.models import User


class LoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ("username", "password")

postly/users/forms/register.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from users.models import User


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = (
            "username",
            "email",
            "password1",
            "password2",
        )

postly/users/forms/reset_password_email.py
from django import forms

from users.models import User


class ResetPasswordEmailForm(forms.Form):
    email = forms.EmailField()

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if not User.objects.filter(email=email).exists():
            raise forms.ValidationError(
                "Account with this email does not exist"
            )

        return email

postly/users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import SetPasswordForm
from django.contrib.auth.tokens import default_token_generator
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.http import urlsafe_base64_decode

from users.forms import (
    EmailForm,
    LoginForm,
    RegisterForm,
    ResetPasswordEmailForm,
)
from users.models import User
from users.services.verification_email import send_verification_email


def registration(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    if request.method == "POST":
        form = RegisterForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()

            send_verification_email(
                request,
                user,
                subject="Registration Confirmation",
                template="users/emails/account_verification_email.html",
            )
            messages.success(request, f"Please check your {user.email}")
            return redirect("users:confirm_email", email=user.email)
    else:
        form = RegisterForm()

    return render(request, "users/register.html", {"form": form})


def confirm_email(request: HttpRequest, email) -> HttpResponse:
    return render(request, "users/confirm_email.html", {"email": email})


def resend_verification_email(
    request: HttpRequest, email: str
) -> HttpResponse | HttpResponseRedirect:
    try:
        user = User.objects.get(email=email)
    except ObjectDoesNotExist:
        messages.error(request, f"User with {email} not exist")
        return redirect("post:post_list")

    send_verification_email(
        request,
        user,
        subject="Registration Confirmation",
        template="users/emails/account_verification_email.html",
    )
    messages.success(
        request, f"We send new confirmation email to {user.email}"
    )
    return render(request, "users/confirm_email.html", {"email": user.email})


def change_email(
    request: HttpRequest, email: str
) -> HttpResponse | HttpResponseRedirect:
    try:
        user = User.objects.get(email=email)
    except ObjectDoesNotExist:
        messages.error(request, f"User with {email} not exist")
        return redirect("post:post_list")

    if request.method == "POST":
        form = EmailForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            send_verification_email(
                request,
                user,
                subject="Registration Confirmation",
                template="users/emails/account_verification_email.html",
            )
            messages.success(
                request, f"We sent new verification email to {user.email}"
            )
            return render(
                request, "users/confirm_email.html", {"email": user.email}
            )
    else:
        form = EmailForm(instance=user)

    return render(
        request,
        "users/change_email.html",
        {
            "form": form,
            "email": email,
        },
    )


def login_view(request: HttpRequest) -> HttpResponse | HttpResponseRedirect:
    if request.method == "POST":
        form = LoginForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect("profile:profile", user.username)

            form.add_error(None, "Invalid login credentials")
    else:
        form = LoginForm()

    return render(request, "users/login.html", {"form": form})


def forgot_password(
    request: HttpRequest,
) -> HttpResponse | HttpResponseRedirect:
    if request.method == "POST":
        form = ResetPasswordEmailForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data["email"]

            try:
                user = User.objects.get(email=email)
            except ObjectDoesNotExist:
                messages.error(request, f"User with {email} not exist")
                return redirect("post:post_list")

            send_verification_email(
                request,
                user,
                subject="Reset Your Password",
                template="users/emails/reset_password_email.html",
            )
            messages.success(
                request,
                "Your password reset link has been sent"
                " to your email address.",
            )
            return redirect("users:login")

    else:
        form = ResetPasswordEmailForm()
    return render(request, "users/forgot_password.html", {"form": form})


def reset_password_validation(
    request: HttpRequest, uidb64: str, token: str
) -> HttpResponseRedirect:
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, ObjectDoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session["uid"] = uid
        messages.success(request, "Please resset your password")
        return redirect("users:reset_password")

    else:
        messages.error(request, "This link is invalid or expired.")
        return redirect("users:login")


def reset_password(
    request: HttpRequest,
) -> HttpResponse | HttpResponseRedirect:
    try:
        pk = request.session.get("uid")
        user = User.objects.get(pk=pk)
    except ObjectDoesNotExist:
        messages.error(request, "Error during reset password")
        return redirect("post:post_list")

    if request.method == "POST":
        form = SetPasswordForm(user, data=request.POST)
        if form.is_valid():
            form.save(user)
            messages.success(request, "You successfully reset your password.")
            return redirect("users:login")
    else:
        form = SetPasswordForm(request.user)
    return render(request, "users/reset_password.html", {"form": form})

postly/users/templates/users/change_email.html
{% extends 'base.html' %}

{% block title %}Change Email{% endblock %}

{% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Change Email</h2>
                <form method="post" class="mt-4" action="{% url 'users:change_email' email %}">
                    {% csrf_token %}

                    {% include 'includes/non_field_errors.html' %}

                    <div class="form-group m-3">
                        <label for="id_email">New Email:</label>
                        <input type="email" name="email" required id="id_email" class="form-control">
                        {% if form.email.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="d-flex justify-content-center m-4">
                        <button type="submit" class="btn btn-success  mr-2">Change email</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

postly/users/templates/users/confirm_email.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "deps/css/my_css.css" %}">

    <link rel="icon" type="image/png" href="{% static "deps/favicon/d-favicon.png" %}">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>

    <header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container"></div>
    </nav>
</header>

    {% include 'includes/notifications.html' %}

    <div class="container mt-4">
        <div class="card mx-auto" style="max-width: 500px;">
            <div class="card-body text-center">
                <h2 class="card-title">Registration Successful!</h2>
                <p class="card-text">Your account has been created successfully. Registration confirmation letter sent to
                    <span class="text-black">{{ email }}</span>. Please check your email.</p>
                <a href="{% url 'users:resend_verification_email' email %}" class="btn btn-primary">Resend email</a>
                <a href="{% url 'users:change_email' email %}" class="btn btn-info">Change email</a>
            </div>
        </div>
    </div>


    <script src="{% static "deps/js/bootstrap/bootstrap.bundle.min.js" %}"></script>
</body>
</html>

postly/users/templates/users/forgot_password.html
{% extends 'base.html' %}

{% block title %}Forgot password{% endblock %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">My email</h2>
                <h4 class="text-center">We will send you resetting password letter</h4>
                <form method="post" action="{% url 'users:forgot_password' %}" class="mt-4">
                    {% csrf_token %}

                    <div class="form-group m-3">
                        <label for="id_email">Email:</label>
                        <input type="email" name="email" autofocus autocapitalize="none"  maxlength="100" required id="id_email" class="form-control"
                               value="{% if form.email.value %}{{ form.email.value }}{% endif %}" placeholder="email@example.com">

                        {% if form.email.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                        {% endif %}
                    </div>


                    <div class="d-flex justify-content-center m-4">
                        <button type="submit" class="btn btn-success  mr-2">Send me a message</button>
                </div>

                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

postly/users/templates/users/login.html
{% extends 'base.html' %}

{% load static %}
{% load account %}
{% load socialaccount %}

{% block title %}Login{% endblock %}

{% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Login</h2>
                <form method="post" action="{% url 'users:login' %}" class="mt-4">
                    {% csrf_token %}

                    {% include 'includes/non_field_errors.html' %}

                    <div class="form-group m-3">
                        <label for="id_username">Username:</label>
                        <input type="text" name="username" autofocus autocapitalize="none" autocomplete="username" maxlength="100" required id="id_username" class="form-control"
                               value="{% if form.username.value %}{{ form.username.value }}{% endif %}">

                        {% if form.username.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                        {% endif %}
                    </div>


                    <div class="form-grou m-3">
                        <label for="id_password">Password:</label>
                        <input type="password" name="password" autocomplete="current-password" required id="id_password" class="form-control">

                        {% if form.password.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.password.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="d-flex justify-content-center m-4">
                        <button type="submit" class="btn btn-success  mr-2">Login</button>

                </form>
                </div>

                <div class="row mt-3">
                    <a href="{% url "users:forgot_password" %}" class="col text-end">Forgot your password?</a> |
                    <a href="{% url "users:register" %}" class="col">Create account</a>
                </div>
                <hr>
                <div class="text-center">
                    <p>Or you can log in through:</p>
                    <a href="{% provider_login_url 'github' %}" class="btn btn-dark">
                        <img class="mx-1" src="{% static "deps/images/github.svg" %}" alt="Catalog Icon" width="16" height="16">
                        GitHub
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

postly/users/templates/users/register.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock %}

{% block content %}
<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Registration</h2>
                <form method="post" action="{% url 'users:register' %}" class="mt-4">
                    {% csrf_token %}

                    {% include 'includes/non_field_errors.html' %}

                    <div class="form-group m-3">
                        <label for="id_username">Username:</label>
                        <input type="text" name="username" required id="id_username" class="form-control"
                               value="{% if form.username.value %}{{ form.username.value }}{% endif %}">
                        {% if form.username.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="form-group m-3">
                        <label for="id_email">Email address:</label>
                        <input type="email" name="email" maxlength="254" id="id_email" class="form-control"
                               value="{% if form.email.value %}{{ form.email.value }}{% endif %}">
                        {% if form.email.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="form-group m-3">
                        <label for="id_password">Password:</label>
                        <input type="password" name="password1" required id="id_password" class="form-control">
                        {% if form.password1.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="form-group m-3">
                        <label for="id_password2">Confirm Password:</label>
                        <input type="password" name="password2" required id="id_password2" class="form-control">
                        {% if form.password2.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="d-flex justify-content-center m-4">
                        <button type="submit" class="btn btn-success">Register</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

postly/users/templates/users/reset_password.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock %}

{% block content %}

<div class="row">
    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                <h2 class="text-center mb-4">Password resetting</h2>
                <form method="post" class="mt-4" action="{% url 'users:reset_password' %}">
                    {% csrf_token %}

                    {% include 'includes/non_field_errors.html' %}

                    <div class="form-group m-3">
                        <label for="id_new-password1">New password:</label>
                        <input type="password" name="new_password1" required id="id_new-password1" class="form-control">
                        {% if form.password1.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.new_password1.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="form-group m-3">
                        <label for="id_new-password2">Confirm new password:</label>
                        <input type="password" name="new_password2" required id="id_new-password2" class="form-control">
                        {% if form.password2.errors %}
                            <div class="alert alert-danger alert-dismissible fade show">{{ form.new_password2.errors }}</div>
                        {% endif %}
                    </div>

                    <div class="d-flex justify-content-center m-4">
                        <button type="submit" class="btn btn-success  mr-2">Reset</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}