postly/core/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("users.urls", namespace="users")),
    path("", include("post.urls", namespace="post")),
    path("", include("userprofile.urls", namespace="profile")),
    path("accounts/", include("allauth.urls")),
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

postly/post/urls.py
from django.urls import path

from post import views

app_name = "post"

urlpatterns = [
    path("", views.post_list, name="post_list"),
    path("create_post/", views.create_post, name="create_post"),
    path("post_list/<str:username>", views.user_posts, name="user_posts"),
    path(
        "following_posts/<str:username>",
        views.following_posts,
        name="following_posts",
    ),
    path("post_detail/<int:post_id>", views.post_detail, name="post_detail"),
    path("post/<int:post_id>/edit", views.edit_post, name="edit_post"),
    path("post/<int:post_id>/delete", views.delete_post, name="delete_post"),
    path(
        "comment/<int:comment_id>/delete",
        views.delete_comment,
        name="delete_comment",
    ),
    path(
        "comment/<int:comment_id>/edit",
        views.edit_comment,
        name="edit_comment",
    ),
    path("like_post/<int:post_id>", views.like_post, name="like_post"),
    path(
        "dislike_post/<int:post_id>", views.dislike_post, name="dislike_post"
    ),
    path(
        "like_comment/<int:comment_id>",
        views.like_comment,
        name="like_comment",
    ),
    path(
        "dislike_comment/<int:comment_id>",
        views.dislike_comment,
        name="dislike_comment",
    ),
]

postly/userprofile/urls.py
from django.urls import path

from userprofile import views

app_name = "profile"

urlpatterns = [
    path("profile/<username>", views.profile, name="profile"),
    path(
        "userprofile/<username>/edit", views.edit_profile, name="edit_profile"
    ),
    path(
        "activate_profile_validation/<uidb64>/<token>",
        views.activate_profile_validation,
        name="activate_profile_validation",
    ),
    path(
        "activate_profile/",
        views.activate_profile,
        name="activate_profile",
    ),
    path("follow/<int:profile_id>", views.follow, name="follow"),
    path("unfollow/<int:profile_id>", views.unfollow, name="unfollow"),
    path("followers/<int:profile_id>", views.followers, name="followers"),
    path("following/<int:profile_id>", views.following, name="following"),
]

postly/userprofile/models/follow.py
from django.db import models


class Follow(models.Model):
    follower = models.ForeignKey(
        "userprofile.UserProfile",
        on_delete=models.SET_NULL,
        related_name="following",
        null=True,
    )
    following = models.ForeignKey(
        "userprofile.UserProfile",
        on_delete=models.CASCADE,
        related_name="followers",
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("follower", "following")

postly/userprofile/models/profile.py
from django.db import models


class UserProfile(models.Model):

    full_name = models.CharField(max_length=255)
    bio = models.TextField()
    avatar = models.ImageField(upload_to="avatars/", blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    user = models.OneToOneField(
        "users.User", on_delete=models.CASCADE, related_name="profile"
    )

    class Meta:
        verbose_name = "Profile"
        verbose_name_plural = "Profiles"

    def __str__(self):
        return f"Profile {self.full_name}"

postly/userprofile/forms.py
from django import forms

from userprofile.models import UserProfile


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ("full_name", "bio", "avatar")

postly/userprofile/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.tokens import default_token_generator
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.utils.http import urlsafe_base64_decode

from userprofile.forms import ProfileForm
from userprofile.models import Follow, UserProfile
from userprofile.selectors import get_followers, get_following

from users.models import User


def activate_profile_validation(
    request: HttpRequest, uidb64: str, token: str
) -> HttpResponseRedirect:
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, ObjectDoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        request.session["uid"] = uid
        messages.success(request, "Please activate your profile")
        return redirect("profile:activate_profile")

    else:
        messages.error(request, "This link is invalid or expired.")
        return redirect("post:post_list")


def activate_profile(
    request: HttpRequest,
) -> HttpResponse | HttpResponseRedirect:
    try:
        uid = request.session.get("uid")
        user = User.objects.get(pk=uid)
    except ObjectDoesNotExist:
        messages.error(request, "Error during activating profile")
        return redirect("post:post_list")

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():

            user_profile = UserProfile(**form.cleaned_data)
            user.profile = user_profile
            user.activate_profile = True
            user_profile.save()
            user.save()

            login(
                request,
                user,
                backend="django.contrib.auth.backends.ModelBackend",
            )
            messages.success(request, "Profile activated")
            return redirect("profile:profile", user.username)
    else:
        form = ProfileForm()

    return render(
        request,
        "userprofile/profile_registration.html",
        {"form": form},
    )


@login_required(login_url="users:login")
def profile(
    request: HttpRequest, username: str
) -> HttpResponse | HttpResponseRedirect:
    try:
        profile_owner = User.objects.get(username=username)
    except ObjectDoesNotExist:
        messages.error(request, "This user does not exist")
        return redirect("post:post_list")

    if not profile_owner.activate_profile and request.user == profile_owner:
        return redirect("users:confirm_email", profile_owner.email)

    if request.user == profile_owner:
        return render(
            request,
            "userprofile/profile.html",
            {"profile": profile_owner.profile},
        )

    return render(
        request,
        "userprofile/profile_view.html",
        {"profile": profile_owner.profile, "user": profile_owner},
    )


@login_required(login_url="users:login")
def edit_profile(
    request: HttpRequest, username: str
) -> HttpResponse | HttpResponseRedirect:
    try:
        user = User.objects.get(username=username)
    except ObjectDoesNotExist:
        messages.error(request, "Error during reset password")
        return redirect("post:post_list")

    if request.user != user:
        messages.error(
            request, "You do not have permission to view this userprofile."
        )
        return redirect("post:post_list")

    if request.method == "POST":
        form = ProfileForm(request.POST, request.FILES, instance=user.profile)
        if form.is_valid():
            form.save()
            messages.success(request, "Profile updated successfully.")
            return redirect("profile:profile", username=username)
    else:
        form = ProfileForm(instance=user.profile)

    return render(
        request,
        "userprofile/edit_profile.html",
        {
            "form": form,
            "user": user,
        },
    )


@login_required(login_url="users:login")
def follow(request: HttpRequest, profile_id: int) -> HttpResponseRedirect:
    try:
        following_profile = UserProfile.objects.get(id=profile_id)
    except ObjectDoesNotExist:
        messages.error(request, "Following profile does not exist")
        return redirect("post:post_list")

    follower_profile = request.user.profile
    if not follower_profile.following.filter(
        following_id=following_profile.id
    ).exists():
        Follow.objects.create(
            follower=follower_profile, following=following_profile
        )
        messages.success(
            request, f"You are following to {following_profile.full_name}."
        )
    return redirect("profile:profile", following_profile.user.username)


@login_required(login_url="users:login")
def unfollow(request: HttpRequest, profile_id: int) -> HttpResponseRedirect:
    try:
        unfollowing_profile = UserProfile.objects.get(id=profile_id)
    except ObjectDoesNotExist:
        messages.error(request, "Following profile does not exist")
        return redirect("post:post_list")

    unfollower_profile = request.user.profile
    follow_obj = unfollower_profile.following.filter(
        following_id=unfollowing_profile.id
    )
    if follow_obj:
        follow_obj.delete()
        messages.error(
            request, f"You are unfollowing {unfollowing_profile.full_name}."
        )

    return redirect("profile:profile", unfollowing_profile.user.username)


@login_required(login_url="users:login")
def followers(request: HttpRequest, profile_id: int) -> HttpResponse:
    try:
        user_followers = get_followers(profile_id)
    except ObjectDoesNotExist:
        messages.error(request, f"Profile {profile_id }does not exist")
        return redirect("post:post_list")

    return render(
        request,
        "userprofile/followers_list.html",
        {"user_followers": user_followers},
    )


@login_required(login_url="users:login")
def following(request: HttpRequest, profile_id: int) -> HttpResponse:
    try:
        following_users = get_following(profile_id)
    except ObjectDoesNotExist:
        messages.error(request, f"Profile {profile_id }does not exist")
        return redirect("post:post_list")

    return render(
        request,
        "userprofile/following_list.html",
        {"following_users": following_users},
    )

postly/userprofile/templates/userprofile/check_email.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "deps/css/bootstrap/bootstrap.min.css" %}">
    <link rel="icon" type="image/png" href="{% static "deps/favicon/d-favicon.png" %}">
    <title>Email Confirmation</title>
</head>
<body>
<div class="container">
        <h2 class="mt-4">Please check your email inbox for confirmation</h2>
        <p>Thank you for your registration.</p>
</div>
</body>
</html>

postly/userprofile/templates/userprofile/edit_profile.html
{% extends 'base.html' %}

{% block title %}Edit Profile{% endblock %}

{% block content %}
<h2>Edit Profile</h2>
    <div class="card">
        <div class="card-body">
            <form method="post" enctype="multipart/form-data" class="mt-4" action="{% url 'profile:edit_profile' user.username %}">

                {% include 'includes/non_field_errors.html' %}

                {% csrf_token %}

                <div class="form-group mt-3">
                    <label for="id_full_name">Full name:</label>
                    <input type="text" name="full_name" value="{{ form.full_name.value }}" maxlength="255" required id="id_full_name" class="form-control">
                </div>

                <div class="form-group mt-3">
                    <label for="id_bio">Bio:</label>
                    <textarea name="bio" cols="40" rows="5" required id="id_bio" class="form-control">{{ form.bio.value }}</textarea>
                </div>

                <div class="mt-3">
                    <label for="formFile" class="form-label">Avatar: </label>
                    <input class="form-control" type="file" id="formFile" name="avatar">
                </div>

                <div class="d-flex justify-content-center m-4">
                    <button type="submit" class="btn btn-dark">Save changes</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

postly/userprofile/templates/userprofile/followers_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <h2>Followers</h2>

  {% if user_followers %}
    <ul>
      {% for follower in user_followers %}
        <li>
          {% if follower.avatar %}
                <img src="{{ follower.avatar.url }}" width="50" height="50">
            {% else %}
                <img src="{% static 'deps/images/default-avatar.png' %}" alt="Default Avatar" width="50" height="50">
          {% endif %}
          <a href="{% url 'profile:profile' username=follower.user.username %}">
            {{ follower.user.username }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No followers yet.</p>
  {% endif %}
{% endblock %}

postly/userprofile/templates/userprofile/following_list.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
  <h2>Following</h2>

  {% if following_users %}
    <ul>
      {% for following in following_users %}
        <li>
          {% if following.avatar %}
                <img src="{{ following.avatar.url }}"  width="50" height="50">
            {% else %}
                <img src="{% static 'deps/images/default-avatar.png' %}" alt="Default Avatar" width="50" height="50">
          {% endif %}
          <a href="{% url 'profile:profile' following.user.username %}">
            {{ following.user.username }}
          </a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>You are not following anyone yet.</p>
  {% endif %}
{% endblock %}

postly/userprofile/templates/userprofile/profile.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Profile{% endblock %}

{% block content %}

<div class="col-md-5 mx-auto">
    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
        <h3 class="text-center mb-4">Profile</h3>
        <div class="row">
                <div class="col-md-12 mb-3 text-center">
                    {% if profile.avatar %}
                        <img src="{{ profile.avatar.url }}" alt="Current Avatar" width="200" height="200">
                    {% else %}
                        <img src="{% static "deps/images/default-avatar.png" %}" alt="Current Avatar" class="img-fluid rounded" width="200" height="200">
                    {% endif %}
                </div>

                <div class="m-4 justify-content-center d-flex">
                    <a href="{% url 'profile:followers' profile.id %}" class="m-2 ">Followers</a>
                    <a href="{% url 'profile:following' profile.id %}" class="m-2">My following</a>
                </div>

                <div class="col-md-12 mb-3 text-center">
                     <label for="id_first_name" class="form-label">Full name:</label>
                    {{ profile.full_name }}
                </div>

                <div class="col-md-12 mb-3 text-center">
                     <label for="id_first_name" class="form-label">Bio:</label>
                    {{ profile.bio }}
                </div>

            <div class=" text-center">
                <a href="{% url 'profile:edit_profile' username=user.username %}" class="btn btn-primary">Edit Profile</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

postly/userprofile/templates/userprofile/profile_registration.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block content %}


<div class="row">
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
            <h2 class="text-center mb-4">Activate profile</h2>
            <form method="post" enctype="multipart/form-data" class="mt-4" action="{% url 'profile:activate_profile' %}">
                {% csrf_token %}

                {% include 'includes/non_field_errors.html' %}

                <div class="form-group mt-3">
                    <label for="id_full_name">Full name:</label>
                    <input type="text" name="full_name" maxlength="255" required id="id_full_name" class="form-control">
                </div>

                <div class="form-group mt-3">
                    <label for="id_bio">Bio:</label>
                    <textarea name="bio" cols="40" rows="5" required id="id_bio" class="form-control"></textarea>
                </div>


                <div class="mt-3">
                    <label for="formFile" class="form-label">Avatar: </label>
                    <input class="form-control" type="file" id="formFile" name="avatar">
                </div>

                <div class="d-flex justify-content-center m-4">
                    <button type="submit" class="btn btn-success">Activate Profile</button>
                </div>
            </form>
        </div>
    </div>
</div>
</div>
{% endblock %}

postly/userprofile/templates/userprofile/profile_view.html
{% extends 'base.html' %}

{% load static %}
{% load profile_tags %}

{% block title %}Profile{% endblock %}

{% block content %}
<div class="col-md-5 mx-auto">
    <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
        <h3 class="text-center mb-4">Profile</h3>
        <div class="row">
            {% csrf_token %}

            <div class="col-md-12 mb-3 text-center">
                {% if profile.avatar %}
                    <img src="{{ profile.avatar.url }}" alt="Current Avatar" width="200" height="200">
                {% else %}
                    <img src="{% static "deps/images/default-avatar.png" %}" alt="Current Avatar" class="img-fluid rounded" width="200" height="200">
                {% endif %}
            </div>

        <div class="col-md-12 mb-3 text-center">
             <label for="id_first_name" class="form-label">Full name:</label>
            {{ profile.full_name }}
        </div>
         <div class="col-md-12 mb-3 text-center" >
             <label for="id_first_name" class="form-label">Bio:</label>
            {{ profile.bio }}
        </div>

        <div class="mt-4 text-center">
            <p><a href="{% url 'post:user_posts' profile.user.username %}" class="btn-secondary">{{ profile.user.username }} posts</a></p>
            {% if not request.user.profile|is_following:profile %}
                <p><a href="{% url "profile:follow"  profile.id %}" class="btn-success">Follow</a></p>
            {% else %}
                <p><a href="{% url "profile:unfollow"  profile.id %}" class="btn-danger">Unfollow</a></p>
            {% endif %}
        </div>

        </div>
    </div>
</div>

{% endblock %}